{{- $image := printf "%s:%s" .Values.image.repository (.Values.image.tag | default "latest") -}}
{{- if .Values.image.digest -}}
{{- $image = printf "%s@%s" .Values.image.repository .Values.image.digest -}}
{{- end }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.pipeline.service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.pipeline.service }}
  template:
    metadata:
      labels:
        app: {{ .Values.pipeline.service }}
        workload: worker
    spec:
      containers:
        - name: worker
          image: {{ $image | quote }}
          env:
            - name: QUEUE_NAME
              value: {{ .Values.queue | quote }}
