#!/usr/bin/env bash
set -euo pipefail

format_rootpath="$1"
format_check_rootpath="$2"
lint_rootpath="$3"
breaking_rootpath="$4"
breaking_explicit_rootpath="$5"
generate_rootpath="$6"
dep_update_rootpath="$7"

workspace_name="${TEST_WORKSPACE:-_main}"
runfiles_root="${TEST_SRCDIR}/${workspace_name}"
if [[ ! -d "${runfiles_root}/examples/protobuf" && -d "${TEST_SRCDIR}/_main/examples/protobuf" ]]; then
  runfiles_root="${TEST_SRCDIR}/_main"
fi

source_example_dir="${runfiles_root}/examples/protobuf"

launcher_path() {
  printf '%s/%s\n' "${runfiles_root}" "$1"
}

format_launcher="$(launcher_path "${format_rootpath}")"
format_check_launcher="$(launcher_path "${format_check_rootpath}")"
lint_launcher="$(launcher_path "${lint_rootpath}")"
breaking_launcher="$(launcher_path "${breaking_rootpath}")"
breaking_explicit_launcher="$(launcher_path "${breaking_explicit_rootpath}")"
generate_launcher="$(launcher_path "${generate_rootpath}")"
dep_update_launcher="$(launcher_path "${dep_update_rootpath}")"

new_workspace() {
  local temp_root
  temp_root="$(mktemp -d)"
  mkdir -p "${temp_root}/examples"
  rsync -aL "${source_example_dir}/" "${temp_root}/examples/protobuf/"
  chmod -R u+w "${temp_root}/examples/protobuf"
  chmod +x "${temp_root}/examples/protobuf/plugins/protoc-gen-example"
  printf '%s\n' "${temp_root}"
}

write_unformatted_proto() {
  local workspace_root="$1"
  cat > "${workspace_root}/examples/protobuf/proto/acme/weather/v1/weather.proto" <<'EOF'
syntax = "proto3";
package acme.weather.v1;
message ForecastRequest{string city=1;}
message ForecastResponse{string summary=1;}
EOF
}

write_breaking_proto() {
  local workspace_root="$1"
  cat > "${workspace_root}/examples/protobuf/proto/acme/weather/v1/weather.proto" <<'EOF'
syntax = "proto3";

package acme.weather.v1;

message ForecastRequest {
  string postal_code = 2;
}

message ForecastResponse {
  string summary = 1;
}
EOF
}

run_launcher() {
  local workspace_root="$1"
  local launcher="$2"
  BUILD_WORKSPACE_DIRECTORY="${workspace_root}" "${launcher}"
}

git_init_main() {
  local workspace_root="$1"
  git -C "${workspace_root}" init -b main >/dev/null
  git -C "${workspace_root}" config user.email "codex@example.com"
  git -C "${workspace_root}" config user.name "Codex"
  git -C "${workspace_root}" add examples/protobuf
  git -C "${workspace_root}" commit -m "baseline" >/dev/null
}

workspace_root="$(new_workspace)"
write_unformatted_proto "${workspace_root}"
if run_launcher "${workspace_root}" "${format_check_launcher}" >/tmp/protobuf-format-check.log 2>&1; then
  echo "expected format_check to fail on unformatted proto" >&2
  exit 1
fi
run_launcher "${workspace_root}" "${format_launcher}" >/tmp/protobuf-format.log 2>&1
grep -Fq 'message ForecastRequest {' "${workspace_root}/examples/protobuf/proto/acme/weather/v1/weather.proto"
run_launcher "${workspace_root}" "${format_check_launcher}" >/tmp/protobuf-format-check-pass.log 2>&1

workspace_root="$(new_workspace)"
run_launcher "${workspace_root}" "${lint_launcher}" >/tmp/protobuf-lint.log 2>&1

workspace_root="$(new_workspace)"
git_init_main "${workspace_root}"
write_breaking_proto "${workspace_root}"
if run_launcher "${workspace_root}" "${breaking_explicit_launcher}" >/tmp/protobuf-breaking-explicit.log 2>&1; then
  echo "expected explicit breaking check to fail" >&2
  exit 1
fi

workspace_root="$(new_workspace)"
git_init_main "${workspace_root}"
remote_root="$(mktemp -d)"
git init --bare "${remote_root}/origin.git" >/dev/null
git -C "${workspace_root}" remote add origin "${remote_root}/origin.git"
git -C "${workspace_root}" push -u origin main >/dev/null
write_breaking_proto "${workspace_root}"
if run_launcher "${workspace_root}" "${breaking_launcher}" >/tmp/protobuf-breaking-default.log 2>&1; then
  echo "expected default breaking check to fail" >&2
  exit 1
fi

workspace_root="$(new_workspace)"
rm -rf "${workspace_root}/examples/protobuf/gen"
run_launcher "${workspace_root}" "${generate_launcher}" >/tmp/protobuf-generate.log 2>&1
generated_file="${workspace_root}/examples/protobuf/gen/example/stub/generated.txt"
test -f "${generated_file}"
grep -Fq 'generated by stub plugin' "${generated_file}"

workspace_root="$(new_workspace)"
rm -f "${workspace_root}/examples/protobuf/buf.lock"
run_launcher "${workspace_root}" "${dep_update_launcher}" >/tmp/protobuf-dep-update.log 2>&1
if [[ -f "${workspace_root}/examples/protobuf/buf.lock" ]]; then
  grep -Fq 'version:' "${workspace_root}/examples/protobuf/buf.lock"
fi
